################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
cpu01-bootROM/source/tables/mac_plc.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/mac_plc.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/mac_plc.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_cosinTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_cosinTable.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_cosinTable.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_dsssDesprdTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_dsssDesprdTable.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_dsssDesprdTable.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_dsssFftDiffSeqTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_dsssFftDiffSeqTable.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_dsssFftDiffSeqTable.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_fskGsnIntFiltTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_fskGsnIntFiltTable.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_fskGsnIntFiltTable.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_fskTxSrcCoefTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_fskTxSrcCoefTable.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_fskTxSrcCoefTable.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_pn9Table.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_pn9Table.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_pn9Table.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_primeprefTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_primeprefTable.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_primeprefTable.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_primetxpreamble.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_primetxpreamble.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_primetxpreamble.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_primrxpreamble.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_primrxpreamble.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_primrxpreamble.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_tf1024pFFTTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_tf1024pFFTTable.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_tf1024pFFTTable.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/tables/phy_tf384pFFTTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables/phy_tf384pFFTTable.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/tables/phy_tf384pFFTTable.pp" --obj_directory="cpu01-bootROM/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


