//Add watch window variables
expRemoveAll
expAdd "sgen.mode" getNatural()
expAdd "sgen.trig" getNatural()
expAdd "sgen.skip_cntr" getNatural()
expAdd "sgen.prescalar" getNatural()
expAdd "sgen.freq" getQValue(15) 
expAdd "sgen.step_max" getNatural()
expAdd "sgen.t_rmpup" getQValue(8)
expAdd "sgen.t_max" getQValue(8)
expAdd "sgen.t_rmpdn" getQValue(8)
expAdd "sgen.t_min" getQValue(8)
expAdd "sgen.task" getNatural()
expAdd "sgen.alpha" getQValue(16)
expAdd "sgen.gain" getQValue(15)
expAdd "sgen.offset" getQValue(15)          
expAdd "sgen.out" getQValue(15)
openAnalysisView('Single Time','C:/TI/controlSUITE/libs/dsp/SGEN/v101/examples_ccsv4/2833x_PROFILE/profile.graphProp')
