################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
cpu01-bootROM/source/DCAN_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/DCAN_Boot.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/DCAN_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/I2C_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/I2C_Boot.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/I2C_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/Parallel_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/Parallel_Boot.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/Parallel_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/SCI_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/SCI_Boot.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/SCI_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/SPI_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/SPI_Boot.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/SPI_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/SelectMode_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/SelectMode_Boot.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/SelectMode_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/Shared_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/Shared_Boot.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/Shared_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/USB_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/USB_Boot.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/USB_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/USB_Boot_Funcs.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/USB_Boot_Funcs.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/USB_Boot_Funcs.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/USB_Structs.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/USB_Structs.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/USB_Structs.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/Vectors_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/Vectors_Boot.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/Vectors_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/c1brom_Init_Boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/c1brom_Init_Boot.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/c1brom_Init_Boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/c1brom_boot.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/c1brom_boot.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/c1brom_boot.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/c1brom_checksum.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/c1brom_checksum.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/c1brom_checksum.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/c1brom_interrupts.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/c1brom_interrupts.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/c1brom_interrupts.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/c1brom_ipc_commands.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/c1brom_ipc_commands.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/c1brom_ipc_commands.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu01-bootROM/source/c1brom_utility_funcs.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/c1brom_utility_funcs.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu01-bootROM/source/tables" --gcc --define=CPU1 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu01-bootROM/source/c1brom_utility_funcs.pp" --obj_directory="cpu01-bootROM/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


