################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
cpu02-bootROM/Cla_Data_Rom/source/tables/CLASinCosTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/Cla_Data_Rom/source/tables/CLASinCosTable.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/source/tables" --gcc --define=CPU2 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu02-bootROM/Cla_Data_Rom/source/tables/CLASinCosTable.pp" --obj_directory="cpu02-bootROM/Cla_Data_Rom/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu02-bootROM/Cla_Data_Rom/source/tables/CLAacosineTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/Cla_Data_Rom/source/tables/CLAacosineTable.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/source/tables" --gcc --define=CPU2 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu02-bootROM/Cla_Data_Rom/source/tables/CLAacosineTable.pp" --obj_directory="cpu02-bootROM/Cla_Data_Rom/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu02-bootROM/Cla_Data_Rom/source/tables/CLAasineTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/Cla_Data_Rom/source/tables/CLAasineTable.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/source/tables" --gcc --define=CPU2 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu02-bootROM/Cla_Data_Rom/source/tables/CLAasineTable.pp" --obj_directory="cpu02-bootROM/Cla_Data_Rom/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu02-bootROM/Cla_Data_Rom/source/tables/CLAatanTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/Cla_Data_Rom/source/tables/CLAatanTable.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/source/tables" --gcc --define=CPU2 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu02-bootROM/Cla_Data_Rom/source/tables/CLAatanTable.pp" --obj_directory="cpu02-bootROM/Cla_Data_Rom/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu02-bootROM/Cla_Data_Rom/source/tables/CLAexpTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/Cla_Data_Rom/source/tables/CLAexpTable.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/source/tables" --gcc --define=CPU2 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu02-bootROM/Cla_Data_Rom/source/tables/CLAexpTable.pp" --obj_directory="cpu02-bootROM/Cla_Data_Rom/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

cpu02-bootROM/Cla_Data_Rom/source/tables/CLAlnTable.obj: C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/Cla_Data_Rom/source/tables/CLAlnTable.asm $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000" -v28 -ml --float_support=fpu32 -g --include_path="C:/ti/ccsv5/tools/compiler/c2000_6.1.3/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_headers/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_common/include/driverlib_inc" --include_path="C:/work/grepos/bootrom_local/Boot_ROM/F2837x_bootROM/customer_relelases/delta_rev0_relelase_oct2_2013/F2837x_rev0_bootROM_source/F2837x_bootROM/cpu02-bootROM/source/tables" --gcc --define=CPU2 --diag_warning=225 --display_error_number --asm_listing --preproc_with_compile --preproc_dependency="cpu02-bootROM/Cla_Data_Rom/source/tables/CLAlnTable.pp" --obj_directory="cpu02-bootROM/Cla_Data_Rom/source/tables" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


